### ISSUE TITLE
render very low

### ISSUE THREAD

**Issue by nppull** [Cnilton/react-native-expandable-list-view#5]
bad performance when my list 30 item

**Comment by paolosantarsiero** [comment]
you try to set animated={false}?

**Comment by Cnilton** [comment]
Hi @nppull, a workaround for your issue is @paolosantarsiero's suggestion. Or maybe some Flatlist related rendering methods. Can you please share a bit of your code for testing and reproducing?

**Comment by Cnilton** [comment]
Hi @nppull and @paolosantarsiero I've implemented a default loader that will appear meanwhile all heights are being calculated, and then it disappears, also the "customLoader" prop, for implementing your own loader. Can you please try using the newest version?
