### ISSUE TITLE
Question - does this component work well with large amount of data?

### ISSUE THREAD

**Issue by edwardigates** [Cnilton/react-native-expandable-list-view#9]
I have a question about performance.
Does it work well with large amounts of data, for instance if my data set has 1000+ items.
Will the animations still be smooth?

**Comment by Cnilton** [comment]
Hi @edwardigates, well, I didn't put this lib through this kind of stress yet.. but anyway, you shouldn't have that many items in any list, I recommend you to use pagination or infinite scroll. If you would like help setting any of my recommendations up, I'm more than happy to help you so! In any case, soon I'll try to bring a stress test!

**Comment by edwardigates** [comment]
Hi @Cnilton , thanks for the response.
 Here's the thing, I want to have an expandable option on some of my list elements. So I tried to do it myself using `Animated.View` and change the height of the element when it has to expand. The items are fetched from a server in batches of 20. At the beginning the animation is smooth, but once I fetch a few more batches, the animation starts to stutter and lag ocasionaly. I guess, it's because I don't use `useNativeDriver` flag with true, but it seems that `useNativeDriver` and height are not compatible  when using `Animated.View`.
That's why I start looking a library that can do that expandable behavior.

**Comment by Cnilton** [comment]
Sorry for taking so long to answer... As I tested locally, I could reproduce a good behavior with 30 ~ 40 items, more than that it starts being a little bit laggy, and it's capped at 50, not rendering anything with more than that. For the time being, it will remain as is, but I'll try to improve its performance in future versions.
